"""Create customer,prescription,medication and user tables

Revision ID: 13b5e7fdcc9e
Revises: a5cf7f4d6cde
Create Date: 2024-09-18 16:41:05.468093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13b5e7fdcc9e'
down_revision: Union[str, None] = 'a5cf7f4d6cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
